services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "230MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true